Feature/content steering
qualabs/common-media-library pull request #30
Opened 2024-03-20 14:21 UTC by fernandocQualabs

## Description
Added content steering functionality into CML 
call content steering server function

2024-03-20 18:12 UTC, mpollingerQualabs commented on lib/src/contentsteering/contentSteering.ts
Is this a test file?

2024-03-20 18:12 UTC, mpollingerQualabs commented on lib/src/contentsteering/contentSteering.ts
> +	'https://fastly.content-steering.com/bbb_hls/master_steering_fastly_https.m3u8thisIsAWrongUri';
Should this be here?

2024-03-20 19:02 UTC, fernandocQualabs commented on lib/src/contentsteering/contentSteering.ts
> +	'https://fastly.content-steering.com/bbb_hls/master_steering_fastly_https.m3u8thisIsAWrongUri';
i commited a test file, my apologies

2024-03-21 12:58 UTC, fyoungqualabs requested changes

2024-03-21 12:58 UTC, fyoungqualabs commented on lib/src/contentsteering/callContentSteeringServer.ts
> +	timeout: number = 5000
Maybe these functions should come in an object named callbacks just like it's implemented in hls.js:
<img width="585" alt="Screenshot 2024-03-21 at 9 26 11 AM" src="https://github.com/qualabs/common-media-library/assets/121059628/d1f687a1-9c49-46f1-a68e-19eea289c062">
On the other hand in dash it also comes inside an object: 
<img width="1031" alt="image" src="https://github.com/qualabs/common-media-library/assets/121059628/12b23674-f929-4964-b280-b2d642480a58">
What do you think?

2024-03-21 12:58 UTC, fyoungqualabs commented on lib/src/contentsteering/callContentSteeringServer.ts
> +	catch (error: any) {
Can we remove this any from here?

2024-03-21 12:58 UTC, fyoungqualabs commented on lib/src/contentsteering/parseM3u8ContentSteeringURI.ts
this function isn't part of the just-fetching logic, maybe we should remove it

2024-03-21 18:30 UTC, coatesjuan requested changes
resolve comments

2024-03-22 13:42 UTC, fyoungqualabs commented on lib/src/contentsteering/parseM3u8ContentSteeringURI.ts
We used this function for testing purposes, I think this function is really useful but maybe should be placed somewhere else.

2024-03-26 18:00 UTC, fyoungqualabs approved these changes

2024-03-26 18:01 UTC, coatesjuan approved these changes

2024-03-26 18:13 UTC, fyoungqualabs commented on lib/src/contentsteering/contentSteering.ts
This file was removed, it was only created for testing purposes.

2024-03-27 14:36 UTC, mpollingerQualabs requested changes

2024-03-27 14:36 UTC, mpollingerQualabs commented on lib/src/contentsteering/callContentSteeringServer.ts
> +	timeout: number = 5000
I would add a comment to this value specifying it's milliseconds. Or change the name of the variable to `timeoutMilliseconds` or something like that, just for clarity and avoiding confusion.
If want to go an extra step, even make it a constant at the top.

2024-03-27 14:36 UTC, mpollingerQualabs commented on lib/src/contentsteering/callContentSteeringServer.ts
> +	catch (error: any) {
Can this be anything other than `any`?

2024-03-27 14:37 UTC, mpollingerQualabs commented on lib/src/contentsteering/callContentSteeringServer.ts
> +	timeout: number = 5000
Btw, i've assumed this is in milliseconds...

2024-04-01 18:04 UTC, closed without merging