Feature/Enhance ID3 Support: Implement APIC Functionality
qualabs/common-media-library pull request #8
Opened 2024-02-14 19:09 UTC by fernandocQualabs

## Description
- Added functionality for parsing APIC Id3 frames (id3 with images). 
- Added Shaka and HLS Id3 unit tests.

- Added new unit tests in CML:
-- readId3Size
-- isId3Header
-- isId3Footer
-- decodeId3Frame

2024-02-14 19:47 UTC, fyoungqualabs commented on lib/src/id3/util/decodeId3ImageFrame.ts
> +type TypedArray = Int8Array | Uint8Array | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | Uint8ClampedArray;
Maybe we should add a comment here explaining why are we adding all these types on the first place

2024-02-14 19:47 UTC, fyoungqualabs commented on lib/test/structuredfield/decodeId3TextFrame.test.ts
> +			size: 2, // required by the _decodeTextFrame function
We should either:
- Remove the '_' in the _decodeTextFrame
- Remove the comment.

2024-02-16 18:48 UTC, fpyoung commented on lib/src/id3/util/decodeId3ImageFrame.ts
> +	 */
Do we want to keep this comment?

2024-02-16 18:48 UTC, fpyoung commented on lib/src/id3/util/isId3Header.ts
> -
is this space a consecuence of linter?

2024-02-16 19:03 UTC, hernanr99 approved these changes
LGTM

2024-02-19 16:33 UTC, fyoungqualabs approved these changes

2024-02-26 19:37 UTC, fyoungqualabs requested changes

2024-02-26 19:37 UTC, fpyoung commented on lib/src/id3/util/decodeId3ImageFrame.ts
> +	// Unlike decodeURIComponent, won't throw on bad encoding.
Maybe we should remove this line if this function doesn't exist.

2024-02-26 19:45 UTC, fpyoung approved these changes

2024-02-26 20:16 UTC, mpollingerQualabs approved these changes

2024-02-27 17:01 UTC, mpollingerQualabs commented on scripts/createReleaseNotes.ts
Do we need to modify this file?

2024-02-27 19:40 UTC, coatesjuan approved these changes

2024-03-05 14:23 UTC, mpollingerQualabs commented
Can this be closed/merged?

2024-03-07 17:45 UTC, closed without merging

2024-03-07 17:46 UTC, fernandocQualabs commented
This is already merged into the main @svta/common-media-library repo